#!/bin/bash

rm -rf debug
rm -f CMakeLists.txt
cp CMakeDebug.txt CMakeLists.txt
mkdir debug
cd debug
echo "rm -rf [^r]* ; cmake -DCMAKE_BUILD_TYPE=debug .." > remake
chmod 777 remake
cmake -DCMAKE_BUILD_TYPE=debug ..
